var packge = require('../package.json');
var log=require("./log"), colors=require("ansi-colors"), black=colors.black, gray=colors.gray, white=colors.white; yellow=colors.yellow; red=colors.red;
log("                                       "+gray("A")+white("API")+gray("KA")+"     ");
log("     "+white("PIKANAAPIKANA")+"    "+gray("A")+white("NA")+"            "+gray("N")+white("A")+gray("A")+"    "+white("NA")+"    ");
log("               "+gray("N")+white("AA")+"    "+gray("N")+white("AA")+"            "+gray("A")+white("A")+gray("P")+"    "+white("AA")+"    ");
log("         "+white("AP")+"    "+white("AA")+gray("P")+"    "+gray("A")+white("AP")+"    "+gray("A")+white("API")+"      "+gray("I")+white("KAN")+gray("AA")+"     ");
log("         "+white("PI")+"   "+gray("A")+white("AP")+"     "+gray("A")+white("PI")+gray("K")+white("ANAA")+gray("P")+"                   ");
log("         "+white("IK")+"  "+white("AAP")+"      "+gray("P")+white("IK")+gray("AN")+"                       ");
log("         "+white("KA")+gray("N")+white("AA")+gray("P")+"       "+gray("I")+white("KA")+"                         ");
log("        "+gray("K")+white("AN")+"           "+gray("K")+white("AN")+"                         ");
log("        "+white("ANA")+"           "+gray("A")+white("NA")+"                         ");
log("       "+gray("A")+white("NA")+"            "+gray("N")+white("AA")+"                         ");
log("     "+gray("K")+white("AN")+gray("A")+"              "+white("API")+gray("KANAAPI")+"                 ");
log("    "+gray("K")+white("A")+gray("N")+"                 "+gray("IKANAAPIKA")+"        "+red('apikana '+packge.version));
log();